# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yemonto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yemonto

  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.1'
  pod 'AppCenter/Push', '~> 1.0.0'
  pod 'AppCenter/Crashes', '~> 1.0.0'
  pod 'AppCenter/Analytics', '~> 1.0.0'
  pod 'AppCenterReactNativeShared', '~> 1.0.0'



  target 'yemontoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'yemonto-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yemonto-tvOS

  target 'yemonto-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
