/**
 * Created by Karan on 2017-10-25.
 */

/*Init*/

export const FIRST_LAUNCH = 'FIRST_LAUNCH'
export const RESET_STATE = 'RESET_STATE'
export const INITIALIZE_STATE = 'INITIALIZE_STATE'
export const UPDATE_PERSIST = 'UPDATE_PERSIST'

/*Navigation Types*/

export const NAVIGATE_TO_LOGIN = 'NAVIGATE_TO_LOGIN'

/*Auth Types*/
export const USERNAME_CHANGE = 'USERNAME_CHANGE'
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE'
export const EMAIL_CHANGE = 'EMAIL_CHANGE'

export const LOGIN_WITH_LINKEDIN = 'LOGIN_WITH_LINKEDIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_LOCAL = 'LOGIN_LOCAL'
export const LOGOUT = 'LOGOUT'

export const EXPERIENCES_LOADED = 'EXPERIENCES_LOADED'
export const LISTINGS_LOADED = 'LISTINGS_LOADED'

/*ProfileTypes*/

export const FETCH_PROFILE_CONTENT = 'FETCH_PROFILE_CONTENT'
export const RECEIVE_PROFILE_CONTENT = 'RECEIVE_PROFILE_CONTENT'
export const ERROR_PROFILE_CONTENT = 'ERROR_PROFILE_CONTENT'
export const SAVE_PROFILE_RATING = 'SAVE_PROFILE_RATING'
export const FIRST_PROFILE_LAUNCH = 'FIRST_PROFILE_LAUNCH'
export const ERROR_PROFILE_LAUNCH = 'ERROR_PROFILE_LAUNCH'
export const PROFILE_LAUNCHED = 'PROFILE_LAUNCHED'
export const ERROR_PROFILE_LAUNCHED = 'ERROR_PROFILE_LAUNCHED'

/*dashboard cards*/

export const RECEIVE_DASHBOARD_CARDS = 'RECEIVE_DASHBOARD_CARDS'
export const FETCH_DASHBOARD_CARDS = 'FETCH_DASHBOARD_CARDS'
export const UPDATE_DASHBOARD_CARDS = 'UPDATE_DASHBOARD_CARDS'
export const ERROR_DASHBOARD_CARDS = 'ERROR_DASHBOARD_CARDS'

export const FETCH_LOOPS = 'FETCH_LOOPS'
export const RECEIVE_LOOPS = 'RECEIVE_LOOPS'
export const ERROR_LOOPS = 'ERROR_LOOPS'
