export const contentStyles = [
  {
    'general': {
      'fontFamily': 'TabletGothic',
      'fontSize': 16,
      'fontWeight': '400',
      'lineHeight': 24,
      'color': '#11114b',
      'marginBottom': 10,
      'marginTop': 0,
    },
    'advance-p': {
      'fontFamily': 'TabletGothic-Thin',
      'lineHeight': 20,
      'fontSize': 24,
    },
    'general-how': {
      'fontFamily': 'TabletGothic',
      'fontSize': 20,
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#11114b',
      'marginBottom': 5,
      'marginTop': 22,
      'marginLeft': 10,
      'marginRight': 10,
    },
    'list-how': {
      'fontFamily': 'TabletGothic',
      'fontSize': 30,
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#11114b',
      'marginBottom': 5,
      'marginTop': 10,
    },
    'general-coach-action': {
      'fontFamily': 'TabletGothic',
      'fontSize': 20,
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#ffffff',
    },
    'general-coach-action-end': {
      'fontFamily': 'TabletGothic',
      'fontSize': 24,
      'fontWeight': '400',
      'lineHeight': 28,
      'color': '#ffffff',
    },
    'general-profile': {
      'fontFamily': 'TabletGothic-Bold',
      'fontSize': 20,
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#11114b',
    },
    'listProfile': {
      'fontFamily': 'TabletGothic',
      'fontSize': 22,
      'fontWeight': '400',
      'lineHeight': 28,
      'color': '#11114b',
      'marginTop': 5,
      'backgroundColor': '#11114b',
    },
    'ulStyle': {
      'marginTop': 10,
    },
    'general-how-ul': {
      'marginTop': 22,
    },
    'listSpan': {
      'fontFamily': 'TabletGothic',
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#11114b',
      'fontSize': 20,
      'marginBottom': 5,
    },
    'textBold': {
      'fontFamily': 'TabletGothic',
      'fontWeight': 'bold',
      'lineHeight': 26,
      'color': '#11114b',
      'fontSize': 20,
    },
    'general-how-italic': {
      'fontFamily': 'TabletGothic',
      'fontStyle': 'italic',
      'fontSize': 20,
      'fontWeight': '400',
      'lineHeight': 26,
      'color': '#11114b',
      'marginBottom': 5,
      'marginTop': 22,
      'marginLeft': 10,
      'marginRight': 10,
    },
  }]
